#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#
 
name: Windows Build
 
run-name: ${{ (github.event_name == 'pull_request' && github.event.pull_request.title || format('Windows Build - {0}', github.ref_name)) }}
 
on:
  pull_request:
  workflow_dispatch:
    inputs:
        CLEAN_ARTIFACTS:
            type: boolean
            description: Use no artifacts for next build (will be saved as clean artifacts)
            required: false
            default: false
  push:
    branches:
      - main
      - development
      - stabilization/**
      - hotfix/**
 
jobs:
 
#### Windows Build ####
    Windows-Profile:
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            platform: Windows
            type: profile
            last_artifact: ${{ github.event.inputs.CLEAN_ARTIFACTS == false }}
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'
        runs-on: DESKTOP-6TC9AUH
 
    Windows-Asset:
        needs: Windows-Profile
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            platform: Windows
            type: asset_profile
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'
        runs-on: DESKTOP-6TC9AUH
 
    Windows-Test:
        needs: Windows-Asset
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            platform: Windows
            type: test_cpu_profile
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'
        runs-on: DESKTOP-6TC9AUH
 
    Windows-Release:
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: release
            platform: Windows
            type: release
            last_artifact: ${{ github.event.inputs.CLEAN_ARTIFACTS == false }}
            msvc_toolset_version: '14.29'
            msvc_platform_toolset: 'v142'
            cmake_version: '~3.24'
        runs-on: DESKTOP-6TC9AUH
